### ISSUE TITLE
[Feature Request] Update existed file in zip support wanted

### ISSUE THREAD

**Issue by leopku** [hidez8891/zip#2]
This is a awesome kit. Thanks for so kindly author.

I had a feature -- get a file from zip and then modify it, finally save the changed file back to the zipfile. 

In my mind, the function maybe should be named like this `func updateFile(...)`

I am new to golang. I don't know if it's hard to implement.

Also, if it was alread supported by existing functions, let me know.

Thanks for your kindness again, @hidez8891.

**Comment by hidez8891** [comment]
`zip.Updater` is modified existed file, but you can only get zip file's header.
You need to use `zip.Reader` to read zip file's content.

```golang
// read file
zr, _ := zip.OpenReader("test.zip")
header := zr.File[0].FileHeader
r, _ := zr.File[0].Open()
// io.Copy(buffer, r) and modify buffer
r.Close()
zr.Close()

// update file
zu, _ := zip.OpenUpdater("test.zip")
zu.File = zu.File[1:]                             // delete first file
w, _ := zu.InsertFile(0, header.Name.Str(), true) // insert file in first position (file's header has Data Descriptor)
io.Copy(w, buffer)                                // writeback
zu.Save()                                         // overwrite
zu.Close()
```

Sorry, I don't have any ideas to implement update method.

**Comment by leopku** [comment]
@hidez8891 thank you very much.
